Port over auth, user, and courseware apps
mitodl/mitx-online pull request #6
Opened 2021-06-30 19:50 UTC by rhysyngsun

#### Pre-Flight checklist

- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Closes #2 

#### What's this PR do?
This PR primarily adds registration and login functionality, although a few other pieces of user-centric functionality was also brought in for the sake of keeping the changes minimal. The source for this implementation is mainly xPro's authentication, user, and courseware applications. I've removed as much as i reasonably can while balancing getting this completed in a timely manner.

#### How should this be manually tested?
- Configure OpenedX and mitX Online to work with each other per `docs/configure_openedx.md`. If you already have configuration in place for xPro in openedx, you'll need to alter those to point to mitx online instead, since the social auth plugin [doesn't work for multiple apps](https://github.com/mitodl/social-auth-mitxpro/issues/14), although this might also be an openedx limitation

- You can register as a new user (http://mitxonline.odl.local:8013/create-account/)
- You can logout
- You can login (http://mitxonline.odl.local:8013/signin/)

2021-07-06 18:12 UTC, rhysyngsun commented
@gsidebo I think this should be all set to review now

2021-07-08 21:41 UTC, gsidebo commented
Just verified that the auth flows all work. The setup documentation needs to be changed in a bunch of ways, but we can tackle that in a different issue

2021-07-08 22:54 UTC, gsidebo requested changes
In addition to the comments: what was your approach to copying things over from `/static`? I see some files that aren't relevant yet and may not be used in the final version, e.g.: `static/js/image_carousel.js`, `static/js/hero.js`, `static/images/certificates/mitx-pro-logo-cer.png`, etc. If the idea is to cull these later, we should probably create some issues

2021-07-08 22:54 UTC, gsidebo commented on docker-compose-notebook.yml
> +  MITX_ONLINE_BASE_URL: ${MITXPRO_BASE_URL:-http://mitxonline.odl.local:8013}
```suggestion
  MITX_ONLINE_BASE_URL: ${MITX_ONLINE_BASE_URL:-http://mitxonline.odl.local:8013}
```

2021-07-08 22:54 UTC, gsidebo commented on .github/workflows/ci.yml
> +          celery -A mitxpro worker -B -l INFO &
~~`mitxpro`~~ `main` I think?

2021-07-08 22:54 UTC, gsidebo commented on main/settings.py
> +VERSION = "0.90.1"
Is this intentional?

2021-07-09 16:05 UTC, rhysyngsun commented
@gsidebo all set for review again

2021-07-09 17:13 UTC, gsidebo approved these changes
Looks great! Feel free to merge after addressing those nitpicks. I'll open a separate issue for updating the edX configuration docs 👍

2021-07-09 20:00 UTC, merged